hero:
  name: 安琪拉
  word: 火焰是我最喜欢的玩具
  Hp: 445.5
#数组
hero_name:
  - 安琪拉
  - 黄忠
  - 小乔
heros:
  - name:  后羿
    word:  周日被我射熄火了
    Hp:  440

hero_name_list:
  - - 安琪拉
    - 后羿
    - 小乔
mobile_parametrize:
  #shouji,appkey
  - [13456755448,0c818521d38759e1]




